name: main
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      # test
      - run: apt install gcc
      - run: make test
